# Generated by Django 3.1.1 on 2020-09-30 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
