# Generated by Django 3.1.1 on 2020-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200930_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['author', 'album', 'title']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='app.Song'),
        ),
    ]
