# Generated by Django 3.1.1 on 2020-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_song_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=1, height_field=400, upload_to='', width_field=400),
            preserve_default=False,
        ),
    ]
