# Generated by Django 3.1.1 on 2020-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201006_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='publish_date',
        ),
    ]
