# Generated by Django 3.1.1 on 2020-10-06 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_playlist_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
