# Generated by Django 3.1.1 on 2020-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201006_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='text',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='text',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
