# Generated by Django 3.1.1 on 2020-10-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201029_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, to='app.Song'),
        ),
    ]
