# Generated by Django 3.1.1 on 2020-10-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20201029_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='song',
            name='liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
