# Generated by Django 3.1.1 on 2020-10-29 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20201029_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='liked',
        ),
        migrations.AddField(
            model_name='song',
            name='songs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
