# Generated by Django 3.1.1 on 2020-10-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201029_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songs',
            new_name='liked',
        ),
    ]
