# Generated by Django 3.1.1 on 2020-10-29 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20201029_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='liked',
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
