# Generated by Django 3.1.1 on 2020-12-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201102_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='author',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
